option(WINTERS_ENABLE_WORKSPACE_MAP "Generate a Visual Studio source map target for browsing Winters." ON)

if(NOT WINTERS_ENABLE_WORKSPACE_MAP)
    return()
endif()

set(WINTERS_CLIENT_DIR "${WINTERS_ROOT_DIR}/Client")
set(WINTERS_SERVER_DIR "${WINTERS_ROOT_DIR}/Server")
set(WINTERS_SHARED_DIR "${WINTERS_ROOT_DIR}/Shared")
set(WINTERS_SHADERS_DIR "${WINTERS_ROOT_DIR}/Shaders")
set(WINTERS_DATA_DIR "${WINTERS_ROOT_DIR}/Data")
set(WINTERS_SERVICES_DIR "${WINTERS_ROOT_DIR}/Services")
set(WINTERS_TOOLS_DIR "${WINTERS_ROOT_DIR}/Tools")

file(GLOB_RECURSE WINTERS_MAP_DOC_FILES CONFIGURE_DEPENDS
    "${WINTERS_ROOT_DIR}/.claude/*.md"
    "${WINTERS_ROOT_DIR}/.claude/commands/*.md"
    "${WINTERS_ROOT_DIR}/.md/*.md"
)

file(GLOB_RECURSE WINTERS_MAP_CLIENT_FILES CONFIGURE_DEPENDS
    "${WINTERS_CLIENT_DIR}/Include/*.vcxproj"
    "${WINTERS_CLIENT_DIR}/Include/*.filters"
    "${WINTERS_CLIENT_DIR}/Private/*.cpp"
    "${WINTERS_CLIENT_DIR}/Private/*.h"
    "${WINTERS_CLIENT_DIR}/Public/*.h"
)

file(GLOB_RECURSE WINTERS_MAP_SERVER_FILES CONFIGURE_DEPENDS
    "${WINTERS_SERVER_DIR}/Include/*.vcxproj"
    "${WINTERS_SERVER_DIR}/Include/*.filters"
    "${WINTERS_SERVER_DIR}/Private/*.cpp"
    "${WINTERS_SERVER_DIR}/Private/*.h"
    "${WINTERS_SERVER_DIR}/Public/*.h"
)

file(GLOB_RECURSE WINTERS_MAP_ENGINE_FILES CONFIGURE_DEPENDS
    "${WINTERS_ENGINE_DIR}/Include/*.h"
    "${WINTERS_ENGINE_DIR}/Private/*.cpp"
    "${WINTERS_ENGINE_DIR}/Private/*.h"
    "${WINTERS_ENGINE_DIR}/Public/*.h"
)

file(GLOB_RECURSE WINTERS_MAP_SHARED_FILES CONFIGURE_DEPENDS
    "${WINTERS_SHARED_DIR}/*.bat"
    "${WINTERS_SHARED_DIR}/*.cpp"
    "${WINTERS_SHARED_DIR}/*.fbs"
    "${WINTERS_SHARED_DIR}/*.go"
    "${WINTERS_SHARED_DIR}/*.h"
    "${WINTERS_SHARED_DIR}/*.hpp"
)

file(GLOB_RECURSE WINTERS_MAP_SHADER_FILES CONFIGURE_DEPENDS
    "${WINTERS_SHADERS_DIR}/*.hlsl"
    "${WINTERS_SHADERS_DIR}/*.hlsli"
)

file(GLOB_RECURSE WINTERS_MAP_DATA_FILES CONFIGURE_DEPENDS
    "${WINTERS_DATA_DIR}/*.dat"
    "${WINTERS_DATA_DIR}/*.json"
    "${WINTERS_DATA_DIR}/*.navgrid"
    "${WINTERS_DATA_DIR}/*.wfx"
)

file(GLOB_RECURSE WINTERS_MAP_SERVICES_FILES CONFIGURE_DEPENDS LIST_DIRECTORIES false
    "${WINTERS_SERVICES_DIR}/*"
)
list(FILTER WINTERS_MAP_SERVICES_FILES EXCLUDE REGEX "/Services/\\.env$")

file(GLOB_RECURSE WINTERS_MAP_TOOLS_FILES CONFIGURE_DEPENDS
    "${WINTERS_TOOLS_DIR}/*.bat"
    "${WINTERS_TOOLS_DIR}/*.cpp"
    "${WINTERS_TOOLS_DIR}/*.filters"
    "${WINTERS_TOOLS_DIR}/*.h"
    "${WINTERS_TOOLS_DIR}/*.hpp"
    "${WINTERS_TOOLS_DIR}/*.vcxproj"
)

set(WINTERS_MAP_ROOT_FILES
    "${WINTERS_ROOT_DIR}/AGENTS.md"
    "${WINTERS_ROOT_DIR}/CLAUDE.md"
    "${WINTERS_ROOT_DIR}/CLAUDE_Legacy.md"
    "${WINTERS_ROOT_DIR}/CMakeLists.txt"
    "${WINTERS_ROOT_DIR}/CMakePresets.json"
    "${WINTERS_ROOT_DIR}/Winters.sln"
)

file(GLOB WINTERS_MAP_CMAKE_FILES CONFIGURE_DEPENDS
    "${WINTERS_ROOT_DIR}/cmake/*.cmake"
)

set(WINTERS_WORKSPACE_MAP_FILES
    ${WINTERS_MAP_ROOT_FILES}
    ${WINTERS_MAP_CMAKE_FILES}
    ${WINTERS_MAP_DOC_FILES}
    ${WINTERS_MAP_CLIENT_FILES}
    ${WINTERS_MAP_SERVER_FILES}
    ${WINTERS_MAP_ENGINE_FILES}
    ${WINTERS_MAP_SHARED_FILES}
    ${WINTERS_MAP_SHADER_FILES}
    ${WINTERS_MAP_DATA_FILES}
    ${WINTERS_MAP_SERVICES_FILES}
    ${WINTERS_MAP_TOOLS_FILES}
)

list(REMOVE_DUPLICATES WINTERS_WORKSPACE_MAP_FILES)

set(WINTERS_MAP_ENGINE_TREE_FILES
    ${WINTERS_MAP_ENGINE_FILES}
)
list(REMOVE_ITEM WINTERS_MAP_ENGINE_TREE_FILES
    "${WINTERS_ENGINE_DIR}/Private/Timer_Manager.cpp"
    "${WINTERS_ENGINE_DIR}/Public/Core/JobCounter.h"
)

add_custom_target(WintersWorkspaceMap SOURCES
    ${WINTERS_WORKSPACE_MAP_FILES}
)

set_target_properties(WintersWorkspaceMap PROPERTIES
    FOLDER "00. Workspace"
)

source_group("00. Root" FILES
    ${WINTERS_MAP_ROOT_FILES}
)
source_group("00. Root\\CMake" FILES
    ${WINTERS_MAP_CMAKE_FILES}
)
source_group("00. Root\\Docs" FILES
    ${WINTERS_MAP_DOC_FILES}
)
source_group(TREE "${WINTERS_CLIENT_DIR}" PREFIX "10. Client" FILES
    ${WINTERS_MAP_CLIENT_FILES}
)
source_group(TREE "${WINTERS_SERVER_DIR}" PREFIX "20. Server Authority" FILES
    ${WINTERS_MAP_SERVER_FILES}
)
source_group(TREE "${WINTERS_ENGINE_DIR}" PREFIX "30. Engine" FILES
    ${WINTERS_MAP_ENGINE_TREE_FILES}
)
source_group(TREE "${WINTERS_SHARED_DIR}" PREFIX "40. Shared" FILES
    ${WINTERS_MAP_SHARED_FILES}
)
source_group(TREE "${WINTERS_SHADERS_DIR}" PREFIX "50. Shaders" FILES
    ${WINTERS_MAP_SHADER_FILES}
)
source_group(TREE "${WINTERS_DATA_DIR}" PREFIX "60. Data" FILES
    ${WINTERS_MAP_DATA_FILES}
)
source_group(TREE "${WINTERS_SERVICES_DIR}" PREFIX "70. Services Backend" FILES
    ${WINTERS_MAP_SERVICES_FILES}
)
source_group(TREE "${WINTERS_TOOLS_DIR}" PREFIX "80. Tools" FILES
    ${WINTERS_MAP_TOOLS_FILES}
)
